// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1U33Uw2ebz_DsJh15jCVW1QvJf4okMrc',
    appId: '1:1080900388377:web:b8bfa91a94ae7a9a8f4c88',
    messagingSenderId: '1080900388377',
    projectId: 'flutter-firebase-1cf76',
    authDomain: 'flutter-firebase-1cf76.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-1cf76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-1cf76.appspot.com',
    measurementId: 'G-120PJ0PVKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6ZZNtkjF-SkjzRKwpfNbV1ivkZTNXyg',
    appId: '1:1080900388377:android:fc0addafcc8360728f4c88',
    messagingSenderId: '1080900388377',
    projectId: 'flutter-firebase-1cf76',
    databaseURL: 'https://flutter-firebase-1cf76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-1cf76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDii_m0IDtiehqHr8fYPuX0DiRtgbQYNzI',
    appId: '1:1080900388377:ios:7bb97afbece4dfd08f4c88',
    messagingSenderId: '1080900388377',
    projectId: 'flutter-firebase-1cf76',
    databaseURL: 'https://flutter-firebase-1cf76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-1cf76.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
